version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: enterlinhas-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lit_admin
      POSTGRES_PASSWORD: lit_secure_pwd
      POSTGRES_DB: enterlinhas_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
